Batch updates
pyspextool/pyspextool pull request #194
Opened 2024-11-26 18:12 UTC by aburgasser

Several updates and some fixes to pieces
batch reduction
- added automatic telluric calibration of individual spectral files, requiring a workaround in telluric/load_spectra.py 
  o note: this throws the following error possibly due to masking issue?

```
/Users/adam/python_codes/pyspextool/src/pyspextool/telluric/core.py:151: RuntimeWarning: invalid value encountered in cast
  stack = np.stack((object_mask.astype(np.uint8),rmask))
```

extraction
- explicitly added A-Sky mode in extract.py (needed for "wide" point sources - comets)

QA:
- updated webpage template to include delta airmass, and individual calibrated spectra

testing:
test_combine.py failed on two issues:
- looking for files 10-11 which weren't present in (local) test_data
- io/read_spectra_fits.py looking for LULABEL keyword which wasn't present in test_data files
note that these might be due to an outdated test_data set; however, I was unable to update the test_data using any of the usual git pull options

other:
- commented out helvetica font family as this was throwing repeated errors on windows machines

2024-11-26 18:22 UTC, aburgasser commented
all tests and checks have passed

2024-11-26 21:53 UTC, michaelcushing requested changes

2024-11-26 21:53 UTC, michaelcushing commented on src/pyspextool/io/read_spectra_fits.py
This needs to stay.  We have to figure out the real problem (which is the test_data).  But I am pretty sure I updated that the last time around.  Ask Kelly?

2024-11-26 21:53 UTC, michaelcushing commented on src/pyspextool/telluric/load_spectra.py
Please start an issue with this so that I can ensure everything else works.

2024-11-26 21:53 UTC, michaelcushing commented on src/pyspextool/telluric/prepare_line.py
Can you start an issue here?  I need to be able to see the errors.

2024-11-26 21:57 UTC, michaelcushing commented on src/pyspextool/telluric/load_spectra.py
Oh one other thing.  When you said you did this for wide-PSF single things like comets, are you just doing A-B where B is a sky? If so, just use the standard A-B mode.  A-Sky is reserved for those who want to create a super sky (which is why I didn't write that part of the code yet).

2024-11-27 18:30 UTC, michaelcushing commented on src/pyspextool/telluric/load_spectra.py
Have you set the number of apertures to find to 1?  If not, then yes it will search for 2 and have a problem.

2024-11-27 19:31 UTC, aburgasser commented on src/pyspextool/telluric/load_spectra.py
rolled back A-Sky for now, procedure above totally works!

2024-11-27 19:31 UTC, aburgasser commented on src/pyspextool/telluric/prepare_line.py
See #193

2024-11-27 19:31 UTC, aburgasser commented
have updated with comments above, all tests have passed

2024-11-27 19:34 UTC, aburgasser commented on src/pyspextool/io/read_spectra_fits.py
also I never found another instance of "LULABEL" in the entire code base - plotting uncertainty uses `ylabel = 'Uncertainty (' + latex_yunits + ')'` (plot/plot_spectra.py line 318)

2024-11-27 19:58 UTC, michaelcushing approved these changes

2024-11-27 19:58 UTC, merged